FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen


COPY . .

EXPOSE 5000

CMD ["uv", "run", "flask", "--app", "main", "run", "--host", "0.0.0.0", "--port", "5000"]
