"""add manager-tenant relationship and manager_id to tickets

Revision ID: 028c794bc565
Revises: 4bc06c161a4a
Create Date: 2026-03-11 20:35:06.057486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028c794bc565'
down_revision = '4bc06c161a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.String(length=36), nullable=True))
        batch_op.create_index('ix_ticket_manager', ['manager_id'], unique=False)
        batch_op.create_foreign_key('fk_tickets_manager_id', 'users', ['manager_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.String(length=36), nullable=True))
        batch_op.create_index('ix_users_manager', ['manager_id'], unique=False)
        batch_op.create_foreign_key('fk_users_manager_id', 'users', ['manager_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_manager_id', type_='foreignkey')
        batch_op.drop_index('ix_users_manager')
        batch_op.drop_column('manager_id')

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tickets_manager_id', type_='foreignkey')
        batch_op.drop_index('ix_ticket_manager')
        batch_op.drop_column('manager_id')

    # ### end Alembic commands ###
