"""normalise: drop ticket.manager_id and redundant ix_users_email

Revision ID: 8548acd75d58
Revises: 028c794bc565
Create Date: 2026-03-11 20:41:35.572766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8548acd75d58'
down_revision = '028c794bc565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_manager'))
        batch_op.drop_constraint(batch_op.f('fk_tickets_manager_id'), type_='foreignkey')
        batch_op.drop_column('manager_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.VARCHAR(length=36), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tickets_manager_id'), 'users', ['manager_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_ticket_manager'), ['manager_id'], unique=False)

    # ### end Alembic commands ###
